### ISSUE TITLE
db hints

### ISSUE THREAD

**Issue by vitaly-t** [evvvvr/q-and-a#1]
About code like this here: https://github.com/evvvvr/q-and-a/blob/master/src/DbService.js
- You should really look at using [Query Files](https://github.com/vitaly-t/pg-promise#query-files). See [QueryFile](http://vitaly-t.github.io/pg-promise/QueryFile.html) and [pg-promise-demo](https://github.com/vitaly-t/pg-promise-demo). And keep your SQL in external files.
- the following does nothing useful:

``` js
function connectToPg() {
    let db;

    try {
        db = Pg(connectionString)
    } catch (err) {
        return Promise.reject(err);
    }

    return Promise.resolve(db);
}
```

You should just declare `db` globally, and that's it, because it will never throw an error, it doesn't do anything at all. Only the actual query methods create a connection, not the database object.

**Comment by evvvvr** [comment]
Thank You for the hints. Especially, didn't know about the second

**Comment by vitaly-t** [comment]
If you are looking to diagnose the connection, see: http://stackoverflow.com/questions/36120435/verify-database-connection-with-pg-promise-when-starting-an-app

**Comment by evvvvr** [comment]
Thank You
